name: Update Pokemon GO Hub News

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

        with:
          node-version: 20

      - run: npm install rss-parser

      - run: node scripts/update-news.js

      - name: Commit Changes

        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add data/news.json

          git commit -m "Automatic Pokémon GO Hub update" || echo "No changes"

          git push
